block-beta
    columns 3
    block:header:3
        columns 3
        alerts options profile
    end
    collections
    block
        columns 1
        filters view
    end
    entities
    footer:3
