on:
  workflow_call:

jobs:
  test:
    name: Test with Java ${{ matrix.jdk }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write

    strategy:
      fail-fast: false
      matrix:
        jdk: [ '11', '17', '21' ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.jdk }}
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      - name: Build with Gradle Wrapper
        run: ./gradlew check --console=plain --warning-mode all
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            "$GITHUB_WORKSPACE/build/test-results/**/*.xml"
            "$GITHUB_WORKSPACE/build/test-results/**/*.trx"
            "$GITHUB_WORKSPACE/build/test-results/**/*.json"